Repository SKHU-BUZZLE/SKHU_Buzzle_FE_v2, pull requests merged in 2025-09, with the labels that each got.

#6 CI/CD 파이프 라인 구축
  .github/CODEOWNERS
  .github/workflows/deploy.yml
  apps/buzzle/src/App.tsx
  packages/design-system/src/components/Test4.tsx
  packages/design-system/src/components/index.ts
Labels: 🚀 Deploy, 📦 Chore

#9 PR Preview 세팅
  .github/workflows/deploy.yml
  .github/workflows/pr-preview-cleanup.yml
  .github/workflows/pr-preview.yml
  apps/buzzle/src/App.tsx
  apps/buzzle/src/main.tsx
  apps/buzzle/src/routes/.gitkeep
  apps/buzzle/src/routes/router.tsx
  apps/buzzle/vite.config.ts
  packages/design-system/src/App.tsx
  packages/design-system/src/components/Test5.tsx
  packages/design-system/src/components/index.ts
Labels: 🚀 Deploy, 📦 Chore

#10 디자인 시스템 세팅
  eslint.config.mjs
  package.json
  packages/design-system/package.json
  packages/design-system/scripts/generate-doc.ts
  packages/design-system/src/App.tsx
  packages/design-system/src/components/Button.tsx
  packages/design-system/src/components/Input/index.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/index.css
  packages/design-system/src/layouts/.gitkeep
  packages/design-system/src/layouts/Layout.tsx
  packages/design-system/src/layouts/MarkdownViewer.tsx
  packages/design-system/src/layouts/Navbar.tsx
  packages/design-system/src/layouts/PropsSpecTable.tsx
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/layouts/StatefulPlayground.tsx
  packages/design-system/src/layouts/StatelessPlayground.tsx
  packages/design-system/src/layouts/ThemeToggle.tsx
  packages/design-system/src/main.tsx
  packages/design-system/src/pages/.gitkeep
  packages/design-system/src/pages/Introduction.tsx
  packages/design-system/src/pages/components/ButtonDoc.tsx
  packages/design-system/src/pages/components/InputDoc.tsx
  packages/design-system/src/pages/foundations/ColorDoc.tsx
  packages/design-system/src/routes/.gitkeep
  packages/design-system/src/routes/index.tsx
  pnpm-lock.yaml
Labels: 📦 Chore, ✨ Feat, 📝 Docs

#13 프로젝트 시작 전 세팅 수정
  .github/workflows/pr-preview.yml
  apps/buzzle/src/App.tsx
  apps/buzzle/src/index.css
  apps/buzzle/src/routes/router.tsx
  apps/buzzle/tsconfig.app.json
  apps/buzzle/vite.config.ts
  eslint.config.mjs
  packages/design-system/scripts/generate-doc.ts
  packages/design-system/src/App.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/index.css
  packages/design-system/src/pages/Introduction.tsx
  packages/design-system/src/pages/components/ButtonDoc.tsx
  packages/design-system/src/pages/components/InputDoc.tsx
  packages/design-system/src/pages/foundations/ColorDoc.tsx
  packages/design-system/src/routes/index.tsx
  packages/design-system/tsconfig.app.json
  packages/design-system/vite.config.ts
Labels: 🚀 Deploy, 📦 Chore, ✅ Test

#16 assets 관련 컴포넌트 & 파일 추가
  apps/buzzle/src/assets/images/buzzle-character.webp
  apps/buzzle/src/assets/images/multi-quiz-guide.webp
  apps/buzzle/src/assets/images/multi-quiz-ready.webp
  apps/buzzle/src/assets/images/multi-quiz-result.webp
  apps/buzzle/src/assets/images/multi-quiz.webp
  apps/buzzle/src/assets/images/note-quiz-guide.webp
  apps/buzzle/src/assets/images/note-quiz-result.webp
  apps/buzzle/src/assets/images/note-quiz.webp
  apps/buzzle/src/assets/images/quiz-creation.webp
  apps/buzzle/src/assets/images/single-quiz-guide.webp
  apps/buzzle/src/assets/images/single-quiz-result.webp
  apps/buzzle/src/assets/images/single-quiz.webp
  package.json
  packages/design-system/package.json
  packages/design-system/scripts/convert-to-webp.ts
  packages/design-system/src/components/icons/BookIcon.tsx
  packages/design-system/src/components/icons/BronzeMedalIcon.tsx
  packages/design-system/src/components/icons/CalendarIcon.tsx
  packages/design-system/src/components/icons/ChevronIcon.tsx
  packages/design-system/src/components/icons/CrownIcon.tsx
  packages/design-system/src/components/icons/CultureIcon.tsx
  packages/design-system/src/components/icons/EconomyIcon.tsx
  packages/design-system/src/components/icons/ErrorIcon.tsx
  packages/design-system/src/components/icons/GoldMedalIcon.tsx
  packages/design-system/src/components/icons/HeartIcon.tsx
  packages/design-system/src/components/icons/HistoryIcon.tsx
  packages/design-system/src/components/icons/HomeIcon.tsx
  packages/design-system/src/components/icons/LogoutIcon.tsx
  packages/design-system/src/components/icons/MedalIcon.tsx
  packages/design-system/src/components/icons/MinusIcon.tsx
  packages/design-system/src/components/icons/MoonIcon.tsx
  packages/design-system/src/components/icons/MultiUserIcon.tsx
  packages/design-system/src/components/icons/NatureIcon.tsx
  packages/design-system/src/components/icons/NoteIcon.tsx
  packages/design-system/src/components/icons/PlusIcon.tsx
  packages/design-system/src/components/icons/RankingIcon.tsx
  packages/design-system/src/components/icons/ScienceIcon.tsx
  packages/design-system/src/components/icons/SilverMedalIcon.tsx
  packages/design-system/src/components/icons/SportsIcon.tsx
  packages/design-system/src/components/icons/SuccessIcon.tsx
  packages/design-system/src/components/icons/SunIcon.tsx
  packages/design-system/src/components/icons/TriviaIcon.tsx
  packages/design-system/src/components/icons/UserIcon.tsx
  packages/design-system/src/components/icons/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/pages/components/IconsDoc.tsx
  packages/design-system/src/routes/index.tsx
  pnpm-lock.yaml
Labels: 🚀 Deploy, 📦 Chore, ✅ Test

#19 디자인 시스템 다크모드에서 인라인 코드의 배경색을 수정
  packages/design-system/src/index.css
Labels: 🎨 Style, 🐞 Bug

#35 BackHeader 구현
  apps/buzzle/src/components/BackHeader.tsx
  apps/buzzle/src/components/BottomNav.tsx
  apps/buzzle/src/pages/review/index.tsx
  apps/buzzle/src/routes/router.tsx
Labels: 🎨 Style, ✨ Feat

#39 ProfileImage 구현
  packages/design-system/src/components/ProfileImage/index.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/mocks/user.ts
  packages/design-system/src/pages/components/ProfileImageDoc.tsx
  packages/design-system/src/routes/index.tsx
  packages/design-system/tsconfig.app.json
  packages/design-system/vite.config.ts
Labels: ✨ Feat

#42 QuizOption 구현
  apps/buzzle/src/index.css
  packages/design-system/src/components/QuizOption/index.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/index.css
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/pages/components/QuizOptionDoc.tsx
  packages/design-system/src/routes/index.tsx
Labels: 🎨 Style, ✨ Feat

#48 Tailwind v4 커스텀 유틸리티 클래스 네이밍 변경
  apps/buzzle/src/components/BottomNav.tsx
  apps/buzzle/src/components/bottomNavBar/index.tsx
  apps/buzzle/src/index.css
  apps/buzzle/src/layouts/HomeFrame.tsx
  apps/buzzle/src/layouts/RootFrame.tsx
  apps/buzzle/src/pages/login/index.tsx
  apps/buzzle/src/pages/multi/index.tsx
  apps/buzzle/src/pages/not-found.tsx
  apps/buzzle/src/pages/ranking/index.tsx
  apps/buzzle/src/pages/review/index.tsx
  apps/buzzle/src/pages/single/index.tsx
  packages/design-system/src/components/LifeCounter/index.tsx
  packages/design-system/src/components/QuizOption/index.tsx
  packages/design-system/src/index.css
  packages/design-system/src/layouts/Layout.tsx
  packages/design-system/src/layouts/Navbar.tsx
  packages/design-system/src/layouts/PropsSpecTable.tsx
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/layouts/StatefulPlayground.tsx
  packages/design-system/src/layouts/StatelessPlayground.tsx
  packages/design-system/src/layouts/ThemeToggle.tsx
  packages/design-system/src/pages/components/IconsDoc.tsx
Labels: 🐞 Bug

#46 Avatar 구현
  packages/design-system/src/components/Avatar/index.tsx
  packages/design-system/src/components/ProfileImage/index.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/pages/components/AvatarDoc.tsx
  packages/design-system/src/routes/index.tsx
Labels: 🎨 Style, ✨ Feat

#52 Button 구현 & StatelessPlayground에 node prop 지원 & 유틸리티 클래스 병합 twm 유틸 함수 구현
  apps/buzzle/src/index.css
  apps/buzzle/src/utils/.gitkeep
  apps/buzzle/src/utils/twm.ts
  packages/design-system/src/components/Button.tsx
  packages/design-system/src/components/Button/index.tsx
  packages/design-system/src/components/QuizOption/index.tsx
  packages/design-system/src/components/icons/LoaderIcon.tsx
  packages/design-system/src/components/icons/index.ts
  packages/design-system/src/components/utils/getValidChildren.ts
  packages/design-system/src/components/utils/isValidIcon.ts
  packages/design-system/src/components/utils/twm.ts
  packages/design-system/src/index.css
  packages/design-system/src/layouts/StatelessPlayground.tsx
  packages/design-system/src/layouts/ThemeToggle.tsx
  packages/design-system/src/pages/Introduction.tsx
  packages/design-system/src/pages/components/ButtonDoc.tsx
  packages/design-system/tsconfig.app.json
  packages/design-system/vite.config.ts
Labels: ✨ Feat

#60 Input & FormField 구현
  packages/design-system/src/components/FormField/index.tsx
  packages/design-system/src/components/FormField/utils/isValidSlot.ts
  packages/design-system/src/components/Input/index.tsx
  packages/design-system/src/components/icons/KeyboardIcon.tsx
  packages/design-system/src/components/icons/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/utils/isValidButton.ts
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/pages/components/FormFieldDoc.tsx
  packages/design-system/src/pages/components/InputDoc.tsx
  packages/design-system/src/routes/index.tsx
Labels: ✨ Feat

#72 배포 yml 수정
  .github/workflows/deploy.yml
Labels: 🚀 Deploy, 📦 Chore, 🐞 Bug

#79 멀티 퀴즈 웹소켓 연결 & 방장/참여자 입장 및 퇴장 구현
  apps/buzzle/package.json
  apps/buzzle/src/apis/multi.ts
  apps/buzzle/src/components/BackHeader.tsx
  apps/buzzle/src/components/quizCategory/index.tsx
  apps/buzzle/src/layouts/BackHeaderFrame.tsx
  apps/buzzle/src/pages/create-room/index.tsx
  apps/buzzle/src/pages/enter-room/index.tsx
  apps/buzzle/src/pages/multi-room/layout.tsx
  apps/buzzle/src/pages/multi-room/lobby.tsx
  apps/buzzle/src/pages/multi-room/play.tsx
  apps/buzzle/src/pages/multi-room/result.tsx
  apps/buzzle/src/pages/multi/index.tsx
  apps/buzzle/src/pages/random-matching/index.tsx
  apps/buzzle/src/routes/router.tsx
  apps/buzzle/src/stores/room.tsx
  apps/buzzle/vite.config.ts
  packages/design-system/src/components/Button/index.tsx
  pnpm-lock.yaml
Labels: 📬 API

#81 TimeProgressBar 구현
  packages/design-system/src/components/TimeProgressBar/index.tsx
  packages/design-system/src/components/hooks/useCountdown.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/pages/components/TimeProgressBarDoc.tsx
  packages/design-system/src/routes/index.tsx
Labels: ✨ Feat

#83 RankedAvatar 구현 및 VictoryStand 구현
  packages/design-system/src/components/RankedAvatar/index.tsx
  packages/design-system/src/components/VictoryStand/index.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/mocks/ranking.ts
  packages/design-system/src/pages/components/RankedAvatarDoc.tsx
  packages/design-system/src/pages/components/VictoryStandDoc.tsx
  packages/design-system/src/routes/index.tsx
Labels: ✨ Feat

#87 멀티 퀴즈 구현 & 빠른 대전 구현
  apps/buzzle/package.json
  apps/buzzle/src/apis/multi.ts
  apps/buzzle/src/pages/create-room/index.tsx
  apps/buzzle/src/pages/enter-room/index.tsx
  apps/buzzle/src/pages/multi-room/layout.tsx
  apps/buzzle/src/pages/multi-room/lobby.tsx
  apps/buzzle/src/pages/multi-room/play.tsx
  apps/buzzle/src/pages/multi-room/result.tsx
  apps/buzzle/src/pages/random-matching/index.tsx
  apps/buzzle/src/stores/room.tsx
  packages/design-system/src/components/QuizOption/index.tsx
  packages/design-system/src/pages/components/QuizOptionDoc.tsx
  pnpm-lock.yaml
Labels: 📬 API, ✨ Feat

#100 UI 리팩토링
  apps/buzzle/src/components/BackHeader.tsx
  apps/buzzle/src/components/MyRankingCard.tsx
  apps/buzzle/src/components/ThemeToggleButton.tsx
  apps/buzzle/src/index.css
  apps/buzzle/src/layouts/BackHeaderFrame.tsx
  apps/buzzle/src/layouts/RootFrame.tsx
  apps/buzzle/src/pages/create-room/index.tsx
  apps/buzzle/src/pages/enter-room/index.tsx
  apps/buzzle/src/pages/home/index.tsx
  apps/buzzle/src/pages/kakao-callback/index.tsx
  apps/buzzle/src/pages/login/index.tsx
  apps/buzzle/src/pages/multi-room/layout.tsx
  apps/buzzle/src/pages/multi-room/lobby.tsx
  apps/buzzle/src/pages/multi-room/play.tsx
  apps/buzzle/src/pages/multi-room/result.tsx
  apps/buzzle/src/pages/multi/index.tsx
  apps/buzzle/src/pages/not-found.tsx
  apps/buzzle/src/pages/random-matching/index.tsx
  apps/buzzle/src/pages/ranking/index.tsx
  apps/buzzle/src/pages/review-quiz/index.tsx
  apps/buzzle/src/pages/review-quiz/play.tsx
  apps/buzzle/src/pages/review-quiz/result.tsx
  apps/buzzle/src/pages/review/detail.tsx
  apps/buzzle/src/pages/review/index.tsx
  apps/buzzle/src/pages/single/index.tsx
  apps/buzzle/src/pages/single/loading.tsx
  apps/buzzle/src/pages/single/play.tsx
  apps/buzzle/src/pages/single/result.tsx
  apps/buzzle/src/routes/router.tsx
  apps/buzzle/src/utils/motionUtils.ts
  packages/design-system/src/components/Button/index.tsx
  packages/design-system/src/components/QuizIntro/index.tsx
  packages/design-system/src/components/RadioGroup/RadioCard.tsx
  packages/design-system/src/components/RadioGroup/RadioRoot.tsx
  packages/design-system/src/components/RadioGroup/RadioTitle.tsx
  packages/design-system/src/components/TimeProgressBar/index.tsx
Labels: 🎨 Style, ♻️ Refactor
